Repository prgrms-be-devcourse/NBE3-4-1-Team04, pull requests merged in 2025-01, with the labels that each got.

#17 Feature/item 4
  Backend/src/main/java/com/example/gc_coffee/GcCoffeeApplication.java
  Backend/src/main/java/com/example/gc_coffee/domain/admin/service/AdminService.java
  Backend/src/main/java/com/example/gc_coffee/domain/cart/controller/CartController.java
  Backend/src/main/java/com/example/gc_coffee/domain/cart/dto/CartDto.java
  Backend/src/main/java/com/example/gc_coffee/domain/cart/entity/Cart.java
  Backend/src/main/java/com/example/gc_coffee/domain/cart/service/CartService.java
  Backend/src/main/java/com/example/gc_coffee/domain/item/controller/ItemController.java
  Backend/src/main/java/com/example/gc_coffee/domain/item/dto/ItemDescriptionDto.java
  Backend/src/main/java/com/example/gc_coffee/domain/item/dto/ItemDto.java
  Backend/src/main/java/com/example/gc_coffee/domain/item/entity/Category.java
  Backend/src/main/java/com/example/gc_coffee/domain/item/entity/Item.java
  Backend/src/main/java/com/example/gc_coffee/domain/item/repository/ItemRepository.java
  Backend/src/main/java/com/example/gc_coffee/domain/item/service/ItemService.java
  Backend/src/main/java/com/example/gc_coffee/domain/order/order/controller/OrderController.java
  Backend/src/main/java/com/example/gc_coffee/domain/order/order/entity/Order.java
  Backend/src/main/java/com/example/gc_coffee/domain/order/order/repository/OrderRepository.java
  Backend/src/main/java/com/example/gc_coffee/domain/order/order/service/OrderService.java
  Backend/src/main/java/com/example/gc_coffee/global/initData/BaseInitData.java
  Backend/src/main/java/com/example/gc_coffee/global/util/Ut.java
  Backend/src/test/java/com/example/gc_coffee/GcCoffeeApplicationTests.java
  Backend/src/test/java/com/example/gc_coffee/domain/item/item/ItemControllerTest.java
Labels: 개발

#20 Refactor/init 19
  Backend/src/main/java/com/example/gc_coffee/domain/item/entity/Item.java
  Backend/src/main/java/com/example/gc_coffee/domain/order/order/entity/Order.java
  Backend/src/main/java/com/example/gc_coffee/global/config/WebConfig.java
  Backend/src/main/java/com/example/gc_coffee/global/springDoc/SpringDocConfig.java
  Backend/src/main/resources/static/favicon.ico
Labels: 수정

#22 Feature/init 21
  frontend/.gitignore
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/public/robots.txt
  frontend/src/App.js
  frontend/src/assets/styles.css
  frontend/src/components/footer/Footer.js
  frontend/src/components/header/Header.js
  frontend/src/components/navigation/Navigation.js
  frontend/src/components/product/ProductStyle1.js
  frontend/src/components/product/ProductStyle2.js
  frontend/src/components/product/ProductStyle3.js
  frontend/src/components/product/ProductStyle4.js
  frontend/src/components/product/ProductStyle5.js
  frontend/src/components/product/ProductStyle6.js
  frontend/src/components/product/ProductStyle7.js
  frontend/src/components/product/ProductStyle8.js
  frontend/src/index.js
  frontend/src/pages/home/Home.js
  frontend/src/reportWebVitals.js
  frontend/src/routes/Router.js
  frontend/src/setupProxy.js
  frontend/src/setupTests.js
Labels: 개발

#24 Feature/item-7
  Backend/src/main/java/com/example/gc_coffee/domain/item/controller/ItemController.java
  Backend/src/main/java/com/example/gc_coffee/domain/item/entity/Item.java
  Backend/src/main/java/com/example/gc_coffee/domain/item/repository/ItemRepository.java
  Backend/src/main/java/com/example/gc_coffee/domain/item/service/ItemService.java
  Backend/src/main/java/com/example/gc_coffee/global/initData/BaseInitData.java
  Backend/src/test/java/com/example/gc_coffee/domain/item/item/ItemControllerTest.java
Labels: 개발

#29 feat:[유저]주문내역조회,수정,취소(Back)(#28)
  Backend/.gitignore
  Backend/src/main/java/com/example/gc_coffee/domain/order/order/controller/OrderController.java
  Backend/src/main/java/com/example/gc_coffee/domain/order/order/dto/OrderRequest.java
  Backend/src/main/java/com/example/gc_coffee/domain/order/order/dto/OrderResponse.java
  Backend/src/main/java/com/example/gc_coffee/domain/order/order/entity/Order.java
  Backend/src/main/java/com/example/gc_coffee/domain/order/order/entity/OrderStatus.java
  Backend/src/main/java/com/example/gc_coffee/domain/order/order/repository/OrderRepository.java
  Backend/src/main/java/com/example/gc_coffee/domain/order/order/service/OrderService.java
  Backend/src/main/java/com/example/gc_coffee/domain/order/orderItem/dto/OrderItemDto.java
  Backend/src/main/java/com/example/gc_coffee/domain/order/orderItem/entity/OrderItem.java
  Backend/src/main/java/com/example/gc_coffee/global/initData/BaseInitData.java
  Backend/src/test/java/com/example/gc_coffee/domain/item/item/ItemControllerTest.java
  Backend/src/test/java/com/example/gc_coffee/domain/order/controller/OrderControllerTest.java
Labels: 개발

#33 Refactor/order-32
  Backend/.gitignore
  Backend/src/main/java/com/example/gc_coffee/domain/item/dto/ItemDto.java
  Backend/src/main/java/com/example/gc_coffee/domain/order/order/controller/OrderController.java
  Backend/src/main/java/com/example/gc_coffee/domain/order/order/dto/OrderRequest.java
  Backend/src/main/java/com/example/gc_coffee/domain/order/order/dto/OrderResponse.java
  Backend/src/main/java/com/example/gc_coffee/domain/order/order/entity/Order.java
  Backend/src/main/java/com/example/gc_coffee/domain/order/order/entity/OrderStatus.java
  Backend/src/main/java/com/example/gc_coffee/domain/order/order/repository/OrderRepository.java
  Backend/src/main/java/com/example/gc_coffee/domain/order/order/service/OrderService.java
  Backend/src/main/java/com/example/gc_coffee/domain/order/orderItem/entity/OrderItem.java
  Backend/src/main/java/com/example/gc_coffee/domain/order/orderItem/repository/OrderItemRepository.java
  Backend/src/main/java/com/example/gc_coffee/global/initData/BaseInitData.java
  Backend/src/test/java/com/example/gc_coffee/domain/order/controller/OrderControllerTest.java
Labels: 개발, 수정

#36 Refactor/init-35
  frontend/src/App.js
  frontend/src/index.js
  frontend/src/routes/Router.js
Labels: 수정

#34 Feat: 관리자 상품등록 기능 구현 및 테스트 코드 추가, ItemController 테스트 코드 오류 수정 #27
  Backend/.gitignore
  Backend/src/main/java/com/example/gc_coffee/domain/admin/controller/AdminController.java
  Backend/src/main/java/com/example/gc_coffee/domain/admin/service/AdminService.java
  Backend/src/main/java/com/example/gc_coffee/domain/item/dto/ItemDto.java
  Backend/src/main/java/com/example/gc_coffee/domain/item/entity/Item.java
  Backend/src/main/java/com/example/gc_coffee/domain/item/service/ItemService.java
  Backend/src/test/java/com/example/gc_coffee/domain/admin/controller/AdminControllerTest.java
  Backend/src/test/java/com/example/gc_coffee/domain/admin/service/AdminServiceTest.java
  Backend/src/test/java/com/example/gc_coffee/domain/item/item/ItemControllerTest.java
Labels: 개발, 수정

#38 Refactor/item-order-37
  Backend/src/main/java/com/example/gc_coffee/domain/admin/controller/AdminController.java
  Backend/src/main/java/com/example/gc_coffee/domain/admin/service/AdminService.java
  Backend/src/main/java/com/example/gc_coffee/domain/item/controller/ItemController.java
  Backend/src/main/java/com/example/gc_coffee/domain/item/dto/ItemDescriptionDto.java
  Backend/src/main/java/com/example/gc_coffee/domain/item/dto/ItemDto.java
  Backend/src/main/java/com/example/gc_coffee/domain/item/entity/Item.java
  Backend/src/main/java/com/example/gc_coffee/domain/item/repository/ItemRepository.java
  Backend/src/main/java/com/example/gc_coffee/domain/item/service/ItemService.java
  Backend/src/main/java/com/example/gc_coffee/domain/order/order/controller/OrderController.java
  Backend/src/main/java/com/example/gc_coffee/domain/order/order/entity/Order.java
  Backend/src/main/java/com/example/gc_coffee/domain/order/order/repository/OrderRepository.java
  Backend/src/main/java/com/example/gc_coffee/domain/order/order/service/OrderService.java
  Backend/src/main/java/com/example/gc_coffee/domain/order/orderItem/entity/OrderItem.java
  Backend/src/main/java/com/example/gc_coffee/global/initData/BaseInitData.java
  Backend/src/test/java/com/example/gc_coffee/domain/admin/controller/AdminControllerTest.java
  Backend/src/test/java/com/example/gc_coffee/domain/admin/service/AdminServiceTest.java
  Backend/src/test/java/com/example/gc_coffee/domain/item/item/ItemControllerTest.java
  Backend/src/test/java/com/example/gc_coffee/domain/order/controller/OrderControllerTest.java
Labels: 수정

#42 Feature/branch-25
  Backend/.gitignore
  Backend/build.gradle
  Backend/src/main/java/com/example/gc_coffee/GcCoffeeApplication.java
  Backend/src/main/java/com/example/gc_coffee/batch/config/OrderStatusUpdateBatchConfig.java
  Backend/src/main/java/com/example/gc_coffee/batch/email/config/MailConfig.java
  Backend/src/main/java/com/example/gc_coffee/batch/email/service/AsyncEmailService.java
  Backend/src/main/java/com/example/gc_coffee/batch/schedule/OrderStatusUpdateSchedule.java
  Backend/src/main/java/com/example/gc_coffee/domain/admin/controller/AdminController.java
  Backend/src/main/java/com/example/gc_coffee/domain/admin/service/AdminService.java
  Backend/src/main/java/com/example/gc_coffee/domain/item/controller/ItemController.java
  Backend/src/main/java/com/example/gc_coffee/domain/item/dto/ItemDescriptionDto.java
  Backend/src/main/java/com/example/gc_coffee/domain/item/dto/ItemDto.java
  Backend/src/main/java/com/example/gc_coffee/domain/item/entity/Item.java
  Backend/src/main/java/com/example/gc_coffee/domain/item/service/ItemService.java
  Backend/src/main/java/com/example/gc_coffee/domain/order/order/controller/OrderController.java
  Backend/src/main/java/com/example/gc_coffee/domain/order/order/dto/OrderRequest.java
  Backend/src/main/java/com/example/gc_coffee/domain/order/order/dto/OrderResponse.java
  Backend/src/main/java/com/example/gc_coffee/domain/order/order/entity/Order.java
  Backend/src/main/java/com/example/gc_coffee/domain/order/order/repository/OrderRepository.java
  Backend/src/main/java/com/example/gc_coffee/domain/order/order/service/OrderService.java
  Backend/src/main/java/com/example/gc_coffee/domain/order/orderItem/entity/OrderItem.java
  Backend/src/main/java/com/example/gc_coffee/global/config/WebConfig.java
  Backend/src/main/java/com/example/gc_coffee/global/exceptions/constant/ErrorCode.java
  Backend/src/main/java/com/example/gc_coffee/global/initData/BaseInitData.java
  Backend/src/main/resources/application.yml
  Backend/src/main/resources/static/favicon.ico
  Backend/src/main/resources/templates/email.html
  Backend/src/test/java/com/example/gc_coffee/GcCoffeeApplicationTests.java
  Backend/src/test/java/com/example/gc_coffee/domain/admin/controller/AdminControllerTest.java
  Backend/src/test/java/com/example/gc_coffee/domain/item/item/ItemControllerTest.java
  Backend/src/test/java/com/example/gc_coffee/domain/order/controller/OrderControllerTest.java
Labels: 개발, 수정

#43 feature/admin-39
  Backend/build.gradle
  Backend/src/main/java/com/example/gc_coffee/GcCoffeeApplication.java
  Backend/src/main/java/com/example/gc_coffee/domain/admin/login/AdminPasswordEncoder.java
  Backend/src/main/java/com/example/gc_coffee/domain/admin/login/SecurityConfig.java
  Backend/src/main/java/com/example/gc_coffee/domain/admin/login/controller/AdminLoginController.java
  Backend/src/main/java/com/example/gc_coffee/domain/admin/login/service/AdminLoginService.java
  Backend/src/main/java/com/example/gc_coffee/global/exceptions/GlobalExceptionHandler.java
  Backend/src/main/resources/admin/adminLogin.html
  Backend/src/test/java/com/example/gc_coffee/domain/admin/login/AdminLoginTest.java
Labels: 개발

#44 Feature/item 11
  frontend/src/App.css
  frontend/src/components/footer/Footer.jsx
  frontend/src/components/navigation/Navigation.css
  frontend/src/pages/home/Home.jsx
  frontend/src/pages/orderlist/OrderList.jsx
  frontend/src/pages/orders/Orders.jsx
  frontend/src/services/productService.js
Labels: 개발

#46 Bug/security-45
  Backend/src/main/java/com/example/gc_coffee/domain/admin/login/SecurityConfig.java
  Backend/src/main/java/com/example/gc_coffee/domain/admin/login/controller/AdminLoginController.java
  Backend/src/main/resources/templates/admin/login.html
  Backend/src/test/java/com/example/gc_coffee/domain/admin/login/AdminLoginTest.java
Labels: 버그, 수정

#48 Refactor/cart-47
  Backend/src/main/java/com/example/gc_coffee/domain/admin/login/SecurityConfig.java
  Backend/src/main/java/com/example/gc_coffee/domain/admin/login/controller/AdminLoginController.java
  Backend/src/main/java/com/example/gc_coffee/domain/cart/controller/CartController.java
  Backend/src/main/java/com/example/gc_coffee/domain/cart/dto/CartDto.java
  Backend/src/main/java/com/example/gc_coffee/domain/cart/entity/Cart.java
  Backend/src/main/java/com/example/gc_coffee/domain/cart/repository/CartRepository.java
  Backend/src/main/java/com/example/gc_coffee/domain/cart/service/CartService.java
  Backend/src/main/java/com/example/gc_coffee/domain/item/entity/Item.java
Labels: 수정

#50 feat: 관리자 로그인 페이지 & 관리자 주문 관리 대시보드 페이지 구현
  frontend/src/App.jsx
  frontend/src/pages/administer/Administer.css
  frontend/src/pages/administer/Administer.jsx
  frontend/src/pages/administer/Dashboard.css
  frontend/src/pages/administer/Dashboard.jsx
  frontend/src/pages/home/Home.css
  frontend/src/pages/home/Home.jsx
  frontend/src/routes/Router.jsx
Labels: 개발

#53 Feature/security-52
  Backend/src/main/java/com/example/gc_coffee/batch/config/OrderStatusUpdateBatchConfig.java
  Backend/src/main/java/com/example/gc_coffee/batch/schedule/OrderStatusUpdateSchedule.java
  Backend/src/main/java/com/example/gc_coffee/domain/admin/login/SecurityConfig.java
  Backend/src/main/java/com/example/gc_coffee/domain/admin/login/controller/AdminLoginController.java
  Backend/src/main/java/com/example/gc_coffee/global/config/WebConfig.java
  Backend/src/main/resources/templates/admin/login.html
  Backend/src/test/java/com/example/gc_coffee/domain/admin/controller/AdminControllerTest.java
  Backend/src/test/java/com/example/gc_coffee/domain/admin/login/AdminLoginTest.java
Labels: 개발

#54 Feature/payment 52
  frontend/src/App.jsx
  frontend/src/pages/administer/Administer.jsx
  frontend/src/pages/home/Home.css
  frontend/src/pages/home/Home.jsx
  frontend/src/pages/orderlist/OrderList.jsx
  frontend/src/pages/orders/Orders.jsx
  frontend/src/pages/payment/Payment.jsx
  frontend/src/pages/payment/PaymentButton.jsx
  frontend/src/pages/payment/ProductList.jsx
  frontend/src/pages/payment/TotalPrice.jsx
  frontend/src/pages/payment/modal/ItemsErrorModal.jsx
  frontend/src/pages/payment/modal/PaymentConfirmation.jsx
  frontend/src/routes/Router.jsx
Labels: 개발

#58 Feature/cart 18
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/localstorage/LocalStorage.jsx
  frontend/src/pages/home/Home.jsx
  frontend/src/pages/payment/Payment.jsx
  frontend/src/pages/payment/ProductList.jsx
Labels: 개발, 수정

#57 feat: 관리자 상품 관리, 주문 조회 페이지 초기 디자인 구현
  frontend/src/pages/administer/ManageProducts.css
  frontend/src/pages/administer/ManageProducts.jsx
  frontend/src/pages/administer/OrderHistory.css
  frontend/src/pages/administer/OrderHistory.jsx
Labels: 개발

#60 Refactor/all 6
  frontend/config-overrides.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/index.js
  frontend/src/setupProxy.js
  public/index.html
Labels: 수정
